POST http://localhost:3000/user/postUser/defed/morcos
Content-Type: application/json

{

}

###
//Get all users
GET http://localhost:3000/user/getUsers
Accept: application/json

###

PUT http://localhost:3000/user/updateUser/0/defed/morcos
Content-Type: application/json

{

}
###
DELETE http://localhost:3000/user/deleteUser/1
Content-Type: application/json

{

}


